### ISSUE TITLE
Mutect: COSMIC contains chr24 and 25?!

### ISSUE THREAD

**Issue by andreas-wilm** [gis-rpd/pipelines#117]

**Comment by justinjj24** [comment]
I see chr24 in the cosmic vcf file but very old version
/mnt/projects/rpd/genomes.testing/MuTect/b37_cosmic_v54_120711.vcf

**Comment by andreas-wilm** [comment]
That's the one we are using. This was a user complaint: 
- 1. why is the file so old
- 2. why does it contain a chr24
- 3. Where was it downloaded / how was it created

**Comment by andreas-wilm** [comment]
File is the original as downloaded from /mnt/projects/rpd/genomes.testing/MuTect/b37_cosmic_v54_120711.vcf and unchanged as of 2017-07-09

**Comment by justinjj24** [comment]
Need to find the right information to generate a newer version of cosmic for b37 which matches v54!
http://gatkforums.broadinstitute.org/firecloud/discussion/2226/cosmic-and-dbsnp-files-for-mutect

https://cancer.sanger.ac.uk/cosmic/download
