### ISSUE TITLE
fluidigm-ht-c1-rnaseq - annotation source name into bam header (rule star)

### ISSUE THREAD

**Issue by justinjj24** [gis-rpd/pipelines#59]
line no. 214,215
gtfsourcefile = os.path.realpath(config['references']['gtfsourcefile'])
fh.write('@CO\tANNOTATIONFILE:%s'.format(gtfsourcefile))

printing
@CO     ANNOTATIONFILE:%s
need to use os.readlink to get the source name of (config['references']['gtfsourcefile'])

**Comment by andreas-wilm** [comment]
Fixed in 7a03d0b (also in production 2016-07 branch)
