### ISSUE TITLE
bcl2fastq run to readunits.yaml

### ISSUE THREAD

**Issue by veeravalli** [gis-rpd/pipelines#64]
Hey Lavanya,

do you think you could write a script that takes a bcl2fastq result folder and creates a readunits yaml file per (component) library? This would require listing all fastq files library, then querying the resp. conf.yaml and dump a file called lib.yaml, so

Read conf.yaml
Per MUX in units of conf.yaml
   Per component library of MUX
      List FastQ files and add to yaml

The corresponding output file for Project_MUX3862/Sample_RHM5468 would then be Project_MUX3862/Sample_RHM5468.yaml and its content looks something like:

samples:
  RHM5468
- some_ru_key
  [- ...]
  readunits:
  ru_key_1:
     flowcell_id: ...
     fq1:  ...
     fq2: ...
     lane_id: ...
     library_id: ...
     rg_id: (auto generated or null for now)
     run_id: ...
  ...

Then we can easily reuse them at a later stage.

Thanks,
Andreas

**Comment by andreas-wilm** [comment]
Completed some time before a6940ce3ead9f09d29807707dd7643b8bcd3abe8
See create_mux_cfg.py
