### ISSUE TITLE
RNAseq: why is outSAMmapqUnique = 50

### ISSUE THREAD

**Issue by andreas-wilm** [gis-rpd/pipelines#72]
Should be 60, right? See also https://www.biostars.org/p/178387/

Pointed out by Teck Por

**Comment by veeravalli** [comment]
TopHat sets the unique mapping quality value as 50 
compatibility between STAR bam with downstream analysis like cufflinks ???
https://sequencing.qcfail.com/articles/mapq-values-are-really-useful-but-their-implementation-is-a-mess/

**Comment by justinjj24** [comment]
can use either 50 or 60 make no difference.
http://gatkforums.broadinstitute.org/gatk/discussion/4285/documentation-error-in-rnaseq-workflow?
