### ISSUE TITLE
File exists, No file or directory (related to parallel conda activations) error for SG10K jobs

### ISSUE THREAD

**Issue by veeravalli** [gis-rpd/pipelines#76]
SG10K pipeline when try to submit hundreds of jobs, the following error occurs at GIS Aquila cluster.

`FileNotFoundError: [Errno 2] No such file or directory: '/mnt/projects/rpd/apps/miniconda3/envs/snakemake-3.7.1/bin/conda'
` 
`
FileExistsError: [Errno 17] File exists: '/mnt/projects/rpd/apps/miniconda3/bin/activate' -> '/mnt/projects/rpd/apps/miniconda3/envs/snakemake-3.7.1/bin/activate'
`
Conda version: conda 4.1.8
Bug issue @ [https://github.com/conda/conda/issues/2837]

 downgrading the conda version to 4.0.5 or 4.0.10 may be required?
[https://kundajelab.github.io/bds_pipeline_modules/troubleshooting.html]

NSCC version is conda 4.0.10

**Comment by andreas-wilm** [comment]
Yes, we saw this in the past after which I downgraded. I though I had created a ticket but can't find it now. Weirdly all conda versions were downgraded except GIS production. 

See also my comment on https://github.com/conda/conda/issues/3001

Anyway, will wait now for new release next week (upgrade needs stopping of cron and completion of running jobs).

**Comment by andreas-wilm** [comment]
Testing was upgraded to 4.3.17 on 4th May 2017

**Comment by andreas-wilm** [comment]
Not observed anymore
