### ISSUE TITLE
GATK recalibration followed by LoFreq somatic variant calling

### ISSUE THREAD

**Issue by wiseflying** [gis-rpd/pipelines#86]
Hi, Andreas and all 

Currently there are two pipelines for somatic variant calling. Sometimes for our projects we need a "hybrid" version of the two for variant calling, meaning GATK recalibration followed by LoFreq. I wonder if it would be possible to have this option also implemented? Or simply allow LoFreq-somatic to accept recalibrated bam files? 

Thanks
Huipeng

**Comment by andreas-wilm** [comment]
Hi Huipeng,

this is possible already but possibly a but cumbersome to use for you:
Run GATK (or Mutect) and then use options --normal-bam and --tumor-bam for Lacer/LoFreq. 

Andreas

**Comment by wiseflying** [comment]
Hi, Andreas

I was thinking of doing this but couldn't find the "bam" options in the lacer-lofreq help manual. Wonder if it is only the description that was missing there. 

Thanks
Huipeng

**Comment by wiseflying** [comment]
Oh, I just found the "bam" option in "lofreq-somatic". Will proceed with that for now. 

Thanks!

Huipeng

**Comment by andreas-wilm** [comment]
Try calling with `--help`. That gives the full usage info
