### ISSUE TITLE
rnaseq: column switch in desc files

### ISSUE THREAD

**Issue by andreas-wilm** [gis-rpd/pipelines#89]
Debarka 29 Dec 2016: "In _RSEM.genes.results.desc files, the last two col names should be swapped"

Justin: "Yes in both fluidigm and star-rsem pipelines! My Apologies some how the last two column header was mistakenly swapped (gene_type - gene_name)."

**Comment by justinjj24** [comment]
Order in the snakemake is correct and the issue arisen for rn5 genome only. fields swapped in the annotation file of rn5 "gene_type and gene_name"
