### ISSUE TITLE
Is --outFilterMultimapNmax set to 1 OK for RSEM?

### ISSUE THREAD

**Issue by GIS-liuxl** [gis-rpd/pipelines#97]
Dear rpd team,

In [RSEM paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-12-323), author mentioned that when using an alternative aligner (default [Bowtie](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2690996/))
> aligners must be configured to report all valid alignments of a read, and not just a single "best" alignment.

In our latest release (2017-01), we set `--outFilterMultimapNmax` to 1 for STAR, which means we only keep those uniquely mapped reads (am I right?). May I know it is OK for using RSEM downstream?

bless~

**Comment by justinjj24** [comment]
Hi,
It's fine to use no big deal since we keep only uniquely mapped reads. STAR mapper uses bowtie2 aligner and provides the rsem compatible transcriptome bam file.

Justin

**Comment by GIS-liuxl** [comment]
Hi @justinjj24,

Thank you very much! So, the transcriptome bam file actually provides multiple alignment information of a read in genome reference mapping even if we only keep the uniquely mapping read (in transcriptome mapping).

bless~

**Comment by justinjj24** [comment]
No. In our pipeline star map the reads against the genome and keep only the uniquely mapped reads and not multimap or best alignment of the multimap, later convert the output genomic alignments in transcriptomic coordinates (Aligned.toTranscriptome.out.bam) for rsem quantification which only recognizes transcriptome coordinate based bam. So in both genomic and transcriptome bam contain only uniquely mapped reads.

But you may see **NH** flag in the transcriptome bam (coordinates are by transcripts, not genes) referring reads with multimap eg."NH:i:3" mapped to three different isoforms of the same gene and not map to different location in the genome.

**Comment by GIS-liuxl** [comment]
Hi @justinjj24 

Oh, I see. Maybe I can understand in this way: the "NH:i:3" case in our pipeline is the counterpart of "all valid alignments" in RSEM paper. The RSEM paper actually means alignment to genome when it mentioned "all valid alignments".

bless~

**Comment by justinjj24** [comment]
RSEM paper suggests when you output multimap from other aligner and feed the bam to rsem for quantification it prefers to choose the best alignment based on their own method, not just the aligner chooses the best alignment by alignment quality of the mapped read.

**Comment by GIS-liuxl** [comment]
@justinjj24 

Thank you very much for your help!

bless~
